version: "3.0"
    
services:
  mysql2:
    image: mysql:8.0.20
    container_name: mysql2
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Lead-138"
      MYSQL_USER: user1
      MYSQL_PASSWORD: "Lead-138"
      MYSQL_DATABASE: "MyDB"
      
  orders2:
    container_name: orders2
    build:
      context: ./orders/
      dockerfile: ./Dockerfile
    image: zmg9046/orders:tag-1.0.0
    ports:
      - "8080:8080"
    environment:
      mysql-servername: mysql2
      mysql-db: "MyDB"
      spring_datasource_username: "user1"
      spring_datasource_password: "Lead-138"
      spring_datasource_url: jdbc:mysql://mysql2:3306/MyDB?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - mysql2
    entrypoint: bash ./wait-for-it.sh mysql2:3306 -t 180 -- java -jar orders.jar

  orders-ui2:
    container_name: orders-ui2
    build:
      context: ./orders-ui/
      dockerfile: ./Dockerfile    
    image: zmg9046/orders-ui:tag-1.0.0
    ports:
      - "5200:80"
    depends_on:
      - orders2
